Compatible with 1.x openai
OpenBMB/XAgent pull request #189
Opened 2023-11-10 04:17 UTC by zhanghy-sketchzh

### 🤔 What is the nature of this change? / 这个变动的性质是？

- [ ] New feature / 新特性提交
- [ ] Fix bug / bug 修复
- [x] Refactor code or style / 重构代码或样式
- [ ] Performance optimization / 性能优化
- [ ] Build optimization / 构建优化
- [ ] Website, documentation, demo improvements / 网站、文档、Demo 改进
- [ ] Test related / 测试相关
- [ ] Other / 其他

### 💡 Background or solution / 需求背景和解决方案

Compatible with 1.x openai

### 📝 Changelog / 更新日志

1. Judging and compatibility according to the user's OpenAI version
2.  Modify the incoming parameters to accommodate the new version of chat.completion
3. Parse the class format of the new version of completion response so that the output follows the dictionary format of the old version

2023-11-10 07:10 UTC, Umpire2018 requested changes
1. This is a new feature instead of code refactor.
2. Please add more unit test if you are available and attach your test result here.
3. Please add more doc-string for this function.

Thanks for you contribution!

2023-11-10 07:10 UTC, Umpire2018 commented on XAgent/ai_functions/request/openai.py
> +    )
I like the style change here.

2023-11-12 23:04 UTC, semikolon commented
What's blocking this? I don't understand.

2023-11-13 00:41 UTC, Umpire2018 commented
@semikolon 
Please kindly refer to [here](https://github.com/OpenBMB/XAgent/pull/189#pullrequestreview-1724155998). Do you suggest a fast merge of this PR? What is your reason? Our team has unanimously agreed that this PR needs to wait for thorough testing, add unit tests, and undergo a complete run-through to ensure no issues arise.

2023-11-13 10:40 UTC, zhanghy-sketchzh commented
running_records:[2023_11_13_09_57_250800778c.zip](https://github.com/OpenBMB/XAgent/files/13333903/2023_11_13_09_57_250800778c.zip)

2023-11-13 10:53 UTC, closed without merging